### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by peterhoeg** [sensu-extensions/sensu-extensions-influxdb2#10]
There are currently no tags or releases created on github which means we need to track master from the Gemfile which is not ideal. It would be great if you started tagging so we could pin to a tag.

**Comment by peterhoeg** [comment]
Or do you have a specific goal in mind before making a proper release?

**Comment by majormoses** [comment]
@peterhoeg ya unfortunately I have been trying to tame the beast of plugins that are not extensions as that is where most of the action happens. I think that we need to start pushing some of the goodness we have worked out into extensions. @luisdavim let's start working together on using the same flow of release process that seems to be working well for the plugins projects.

**Comment by luisdavim** [comment]
Hi,

Sorry for the delay, @majormoses do you have a link where this process is documented?

Thanks,
Luis

**Comment by majormoses** [comment]
@luisdavim let's sync up on this but the process for plugins looks like this: https://github.com/sensu-plugins/documentation/blob/master/docs/b_and_r.md but I know we will need to do a bit more than that since there is not all the automation for it. At the next maintainer chat we will discuss bringing the maturity of plugins to extensions.

**Comment by peterhoeg** [comment]
Thank you for releasing 0.1.0!
